# Generated by Django 5.1.6 on 2025-02-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valueselection',
            old_name='cost_score',
            new_name='customer_experience',
        ),
        migrations.RenameField(
            model_name='valueselection',
            old_name='experience_score',
            new_name='increase_revenue',
        ),
        migrations.RemoveField(
            model_name='valueselection',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='valueselection',
            name='regulative_score',
        ),
        migrations.RemoveField(
            model_name='valueselection',
            name='revenue',
        ),
        migrations.RemoveField(
            model_name='valueselection',
            name='revenue_score',
        ),
        migrations.RemoveField(
            model_name='valueselection',
            name='strategy_score',
        ),
        migrations.AlterField(
            model_name='valueselection',
            name='cost_optimization',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='valueselection',
            name='regulative',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='valueselection',
            name='strategy',
            field=models.IntegerField(default=0),
        ),
    ]
