# Generated by Django 5.1.6 on 2025-02-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0002_rename_cost_score_valueselection_customer_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valueselection',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
