# Generated by Django 5.1.6 on 2025-02-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0003_valueselection_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valueselection',
            old_name='strategy',
            new_name='other_strategy',
        ),
        migrations.AddField(
            model_name='valueselection',
            name='category',
            field=models.CharField(default='Undefined', max_length=255),
        ),
        migrations.AddField(
            model_name='valueselection',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='valueselection',
            name='cost_optimization',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='valueselection',
            name='customer_experience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='valueselection',
            name='increase_revenue',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='valueselection',
            name='project_name',
            field=models.CharField(default='Default Project', max_length=255),
        ),
        migrations.AlterField(
            model_name='valueselection',
            name='regulative',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='valueselection',
            name='total_score',
            field=models.IntegerField(),
        ),
    ]
