# Generated by Django 5.1.6 on 2025-02-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0005_rename_other_strategy_valueselection_strategy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valueselection',
            old_name='total_score',
            new_name='budget',
        ),
        migrations.AddField(
            model_name='valueselection',
            name='complexity_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='valueselection',
            name='department_processes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='valueselection',
            name='human_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='valueselection',
            name='integrations_systems',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='valueselection',
            name='overall_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='valueselection',
            name='value_total',
            field=models.IntegerField(default=0),
        ),
    ]
